// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWyE5N9eW0jgPA2lXkKkZ3IbK5Xx2iLUE',
    appId: '1:168113650537:web:f31f772c414ea0b7329bf8',
    messagingSenderId: '168113650537',
    projectId: 'stayfit-b2fc8',
    authDomain: 'stayfit-b2fc8.firebaseapp.com',
    storageBucket: 'stayfit-b2fc8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpSGpET0lbJpSBsuqVCveGut_dVsskbCE',
    appId: '1:168113650537:android:f0c6069183aac343329bf8',
    messagingSenderId: '168113650537',
    projectId: 'stayfit-b2fc8',
    storageBucket: 'stayfit-b2fc8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzN-7Bfous5UNStdVwofJmBrZebItgR5k',
    appId: '1:168113650537:ios:246f57fde7587e3f329bf8',
    messagingSenderId: '168113650537',
    projectId: 'stayfit-b2fc8',
    storageBucket: 'stayfit-b2fc8.appspot.com',
    androidClientId: '168113650537-v26gdqmie378jccd2k465tm9tdhf75eb.apps.googleusercontent.com',
    iosClientId: '168113650537-6ogun78j0cr035g1ov16hcf2l5vuuhng.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessAppLive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzN-7Bfous5UNStdVwofJmBrZebItgR5k',
    appId: '1:168113650537:ios:246f57fde7587e3f329bf8',
    messagingSenderId: '168113650537',
    projectId: 'stayfit-b2fc8',
    storageBucket: 'stayfit-b2fc8.appspot.com',
    androidClientId: '168113650537-v26gdqmie378jccd2k465tm9tdhf75eb.apps.googleusercontent.com',
    iosClientId: '168113650537-6ogun78j0cr035g1ov16hcf2l5vuuhng.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessAppLive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWyE5N9eW0jgPA2lXkKkZ3IbK5Xx2iLUE',
    appId: '1:168113650537:web:bcdfb311f6bafcec329bf8',
    messagingSenderId: '168113650537',
    projectId: 'stayfit-b2fc8',
    authDomain: 'stayfit-b2fc8.firebaseapp.com',
    storageBucket: 'stayfit-b2fc8.appspot.com',
  );
}
