name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up the latest stable version of the Dart SDK with Flutter.
      - uses: dart-lang/setup-dart@v1
        with:
          flutter: true

      - name: Install dependencies
        run: flutter pub get

      # Uncomment this step to verify the use of 'dart format' on each commit.
      # - name: Verify formatting
      #   run: flutter format --output=none --set-exit-if-changed .

      # Analyze Flutter project source
      - name: Analyze project source
        run: flutter analyze

      # Run Flutter tests
      - name: Run tests
        run: flutter test
